// Initally converted from bjson-schema.json with https://transform.tools/json-schema-to-typescript

export interface BJson {
    notes?: Note[]
    bpm?:
    | number
    | {
        time: number
        bpm: number
    }[]
    measureConfig?: MeasureConfig | MeasureConfig[]
    bookmarks?: {
        time: number
        title?: string
        description?: string
    }[]
    annotations?: {
        time: number
        text?: string
    }[]
    audio?: string
    /**
     * Image used as a background when showing this beatmap.
     */
    image?: string
    video?: string
    videoOffset?: number
    offset: number
    leadIn?: number
    previewTime?: number
    /**
     * Unique identifier. Uses filename if not specified. Doesn't need to be in any particular format. By default, this will be generated by DrumGame as a GUID.
     */
    id?: string
    relativeVolume?: number
    spacingMultiplier?: 1 | 2
    /**
     * Intended game version for this beatmap.
     */
    gameVersion?: number
    title?: string
    artist?: string
    album?: string
    mapper?: string
    difficulty?: "Easy" | "Normal" | "Insane" | "Hard" | "Expert" | "Expert+"
    difficultyName?: string
    description?: string
    tags?: string
    beatmapVersion?: number
    /**
     * The MD5 hash of the audio resource. Useful for restoring audio file if it is lost. Indicate other hashing algorithms with the {algorithm}:{hash} format.
     */
    audioHash?: string
    youTubeID?: string
    youTubeOffset?: number
    ototoyAlbumID?: number
    amazonASIN?: string
    bandcampArtist?: string
    bandcampTrack?: string
    /**
     * Origin of the song, such as another game, movie, anime, or event. Many songs should leave this empty.
     */
    songSource?: string
    /**
     * This should be where the map was downloaded from (or where it can be publicy shared).
     */
    mapSourceUrl?: string
    creationTimeUtc?: string
    /**
     * Only use for urls/sources that do not have official fields. For example, if you want to link a YouTube video, put that in the `youtubeId` field instead of here.
     */
    links?:
    | []
    | [
        {
            label: string
            url: string
            description?: string
        }
    ]
}
export interface MeasureConfig {
    time?: number
    beats: number
}
export interface Note {
    tick: number
    additionalProperties?: false
    time: number
    duration?: number
    modifier?: "accent" | "ghost"
    sticking?: "left" | "right"
    channel: DrumChannel

    voice: number // this gets set after we load the JSON
    noteMapping: [position: number, codePoint: string] // this gets set later
}

export type DrumChannel =
    | "snare"
    | "bass"
    | "hihat"
    | "crash"
    | "open-hihat"
    | "half-hihat"
    | "ride"
    | "ride-bell"
    | "sidestick"
    | "high-tom"
    | "mid-tom"
    | "low-tom"
    | "hihat-pedal"
    | "splash"
    | "china"
    | "rim"