// <auto-generated />
using DrumGame.Game.Stores.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrumGame.Game.Migrations
{
    [DbContext(typeof(DrumDbContext))]
    [Migration("20220202195033_init")]
    partial class init1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("DrumGame.Game.Stores.DB.ReplayInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccuracyHit")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccuracyTotal")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CompleteTimeTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapId")
                        .HasColumnType("TEXT");

                    b.Property<long>("MaxCombo")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Replays");
                });
#pragma warning restore 612, 618
        }
    }
}
